input_size: 64
num_epochs: 50

pl_module:
  _target_: ml_runner.module.generic.GenericModule
  model: ${model}
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss
  optimizer: ${optimizer}
  metrics: ${metrics}
  scheduler: ${scheduler}

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  max_epochs: ${num_epochs}
  callbacks: ${oc.dict.values:callbacks}

train_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: 1024
  dataset: ${dataset.train}

val_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: 1024
  dataset: ${dataset.val}

entrypoint:
  _target_: ml_runner.entrypoint.fit.fit
  pl_module: ${pl_module}
  trainer: ${trainer}
  train_loader: ${train_loader}
  val_loader: ${val_loader}

defaults:
  - _self_
  - callbacks:
    - lr_monitor
  - dataset: cifar10
  - model: resnet18
  - optimizer: sgd
  - metrics:
    - accuracy
    - precision
  - scheduler: cosine
