batch_size: 1024
input_size: 64
num_epochs: 50
num_workers: 10

pl_module:
  _target_: ml_runner.module.generic.GenericModule
  model: ${model}
  loss_fn: ${loss}
  optimizer: ${optimizer}
  metrics: ${metrics}
  scheduler: ${scheduler}

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  max_epochs: ${num_epochs}
  callbacks: ${oc.dict.values:callbacks}

train_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  dataset: ${dataset.train}
  shuffle: True
  num_workers: ${num_workers}

val_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: ${batch_size}
  dataset: ${dataset.val}
  shuffle: False
  num_workers: ${num_workers}

entrypoint:
  _target_: ml_runner.entrypoint.fit.fit
  pl_module: ${pl_module}
  trainer: ${trainer}
  train_loader: ${train_loader}
  val_loader: ${val_loader}

defaults:
  - _self_
  - callbacks:
    - lr_monitor
  - dataset: cifar10
  - loss: crossentropy
  - model: resnet18
  - optimizer: sgd
  - metrics:
    - accuracy
    - precision
  - scheduler: cosine
