_target_: torchvision.datasets.CIFAR10
root: /tmp/cifar10
transform:
  _target_: torchvision.transforms.Compose
  transforms:
    - _target_: torchvision.transforms.Resize
      size: ${input_size}
    - _target_: torchvision.transforms.ToTensor
download: True
