num_classes: 100
train:
  _target_: torchvision.datasets.CIFAR100
  train: True
  root: /tmp/cifar100
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: ${input_size}
      - _target_: torchvision.transforms.ToTensor
  download: True
val:
  _target_: torchvision.datasets.CIFAR100
  train: False
  root: /tmp/cifar100
  transform:
    _target_: torchvision.transforms.Compose
    transforms:
      - _target_: torchvision.transforms.Resize
        size: ${input_size}
      - _target_: torchvision.transforms.ToTensor
  download: True
